name: real_time_plot_formal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^24.2.7+1
  path_provider: ^2.1.2
  permission_handler: ^8.3.0
  butter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/STAND.onnx
    - assets/DB.onnx
    - assets/SLEEP.onnx
    - assets/testdata/chirustand03.csv



